### PR TITLE
Improve results UI

### PR DESCRIPTION
**Pull request by SandroMachado**
This pull request improves the application results UI and removes unused code. 

Do you have any updates about releasing this application to the google play store? If you want I can release it using my developer account.  

Thanks for your your great work.

### CODE REVIEW

**Comment by dweinstein** [comment]
@SandroMachado thanks for your contributions. we'll be getting the app on the store soon.

**Comment by Fuzion24** [comment]
Your changes have been cherry-picked into master since they wouldn't merge cleanly because of some of my changes.  Again, thanks for the work!

**Comment by SandroMachado** [comment]
Great! Thanks :+1:

**Comment by dweinstein** [comment]
@SandroMachado the app is now on the play store, see #34

**Comment by SandroMachado** [comment]
Great! Thanks =)
Can you also create a release on the github with this version and add the play store apk to the release? This will allow everyone to download the code and test a specific feature or bug only available on that version.

**Comment by Fuzion24** [comment]
How about we tag the commits that we push to the play store?

**Comment by SandroMachado** [comment]
I was thinking of creating a release (1.0?) from this commit (https://github.com/nowsecure/android-vts/commit/98f404eaf83b212856a6a7608811b52b5c83d5c6) to be available in the [releases tag](https://github.com/nowsecure/android-vts/releases).

**Pull request closed without merging**
