### PR TITLE
Initial support for sharing results

### PR DESCRIPTION
**Pull request by dweinstein**
initially addresses #6 by adding support to share JSON serialized result (e.g.,
  for adding into the clipboard)

### CODE REVIEW

**Comment by dweinstein** [comment]
cc @SandroMachado

**Comment by SandroMachado** [comment]
@dweinstein great!

WDYT of adding the sharing action as an option in the overflow menu?
With this we don't need to `hack` the FAB buttons setting their visibility.

If you want I can make a commit with that change.

screen shot 2015-11-11 at 23 48 01

**Comment by dweinstein** [comment]
Sure!

**Comment by SandroMachado** [comment]
I cannot make commits to your branch since I don't have access to the repository. So my suggestion is rebase my fork with the project, clone your branch, make my commit and submit a PR with my commit. Do you have a better alternative?

**Comment by dweinstein** [comment]
if @Fuzion24 wants to merge this now (it should be stable) you can PR off the new master as well. in the future I'll open PRs from my own fork if that makes it any easier.

**Comment by Fuzion24** [comment]
kk, i'll give this a test in the morning.

**Pull request merged**
